name: Build and Test SpatiaLite Extension

on:
  workflow_dispatch: # Trigger manual melalui GitHub Actions UI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Common steps for all platforms
    - name: Setup Environment
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "No additional setup for Windows"
        elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential wget libsqlite3-dev libxml2-dev zlib1g-dev
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew update
          brew install sqlite libxml2
        fi

    - name: Download SpatiaLite
      run: |
        wget https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-amalgamation-3.0.1.tar.gz
        tar -xvzf libspatialite-amalgamation-3.0.1.tar.gz
        cd libspatialite-amalgamation-3.0.1

    - name: Build SpatiaLite
      run: |
        cd libspatialite-amalgamation-3.0.1
        ./configure --prefix=$PWD/build
        make
        make install

    - name: Test SpatiaLite Extension
      run: |
        sqlite3 :memory: \
          -cmd ".load ./build/lib/mod_spatialite.so" \
          "SELECT spatialite_version();" \
          ".quit"

    - name: Archive Build (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: spatialite-extension-${{ matrix.os }}
        path: libspatialite-amalgamation-3.0.1/build/
